import { auth } from '@/configurations/auth';
import MainHeader from '../components/main-header';
import './globals.css';
import Link from 'next/link';
import classes from './page.module.css'

export const metadata = {
  title: 'Favorite Cities',
  description: 'Generated by create next app',
};

const session = await auth();

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <div id='modal'></div>
        <MainHeader />
        {!session?.user && (
          <div className={classes.container}>
            <h3>
              ! To be able to save your favorite places please <Link href='/account'>Log-In</Link> !
            </h3>
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
